// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT3-H6cBk20MLNkjlwLM3QuPTBJ9ChGeg',
    appId: '1:456618117588:web:16f623ab0b11aa12602e41',
    messagingSenderId: '456618117588',
    projectId: 'muber-9641d',
    authDomain: 'muber-9641d.firebaseapp.com',
    storageBucket: 'muber-9641d.appspot.com',
    measurementId: 'G-F9RLHY6VD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKAvXO96rQWi2bh80lFdE0BQrFh0RBlrE',
    appId: '1:456618117588:android:d2aa263b3179a509602e41',
    messagingSenderId: '456618117588',
    projectId: 'muber-9641d',
    storageBucket: 'muber-9641d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJZyogMSzEryC-k4Xvxt7MSiJb9nh0Zxk',
    appId: '1:456618117588:ios:0c33642ae75fc844602e41',
    messagingSenderId: '456618117588',
    projectId: 'muber-9641d',
    storageBucket: 'muber-9641d.appspot.com',
    iosBundleId: 'com.example.driversApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJZyogMSzEryC-k4Xvxt7MSiJb9nh0Zxk',
    appId: '1:456618117588:ios:0c33642ae75fc844602e41',
    messagingSenderId: '456618117588',
    projectId: 'muber-9641d',
    storageBucket: 'muber-9641d.appspot.com',
    iosBundleId: 'com.example.driversApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT3-H6cBk20MLNkjlwLM3QuPTBJ9ChGeg',
    appId: '1:456618117588:web:49ba27eee2a38a1e602e41',
    messagingSenderId: '456618117588',
    projectId: 'muber-9641d',
    authDomain: 'muber-9641d.firebaseapp.com',
    storageBucket: 'muber-9641d.appspot.com',
    measurementId: 'G-GN9MCMKV68',
  );
}
